spring:
  hibernate:
    jpa:
      ddl-auto : create
server:
  port: 8082

#########################################################
############# SYMPHONY CONFIG ###########################
#########################################################
sessionAuthURL: https://develop2-api.symphony.com:8444/sessionauth
keyAuthUrl: https://develop2-api.symphony.com:8444/keyauth
botCertPath: cert_key.p12
botCertPassword: changeit
botEmailAddress: bot.user31
agentAPIEndpoint: https://develop2.symphony.com/agent
podAPIEndpoint: https://develop2.symphony.com/pod

#########################################################
############# ACTION ITEM TRIGGER CONFIG ################
#########################################################
taskReminderInterval: 24
maxAllowedWrongInputs: 2
#########################################################
################## JIRA CONFIG ##########################
#########################################################
jira:
  oauth :
    consumerKey: OauthKey
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALAM7NzrfDg9bOSstvkBS2uBhRO4LVvLZafK6kwGmWFmykI/qiz68xgq6iJIrGvFTT4PYJ+AcKneDESNR1n05G2UQ8NxOM1TkcQAKBhZXNRjbweKeP+MDNPfYfF3LSQuyYa4GbDRuCeeyeEdaitHu97/oaAdDQnRUX90F7DtkOJxAgMBAAECgYB37cYp1Q2BLm8Q9IuM45HiQZBLV6smnk+412V2twQjsydTrBUcoTObIhjvk/xJSlYNUeJrpc6aGVbYGDokEMzOqyuJOnwlo8KF6Qzd8+KgPUj/kooPTsES6GiNYFSf8PQoXS/XnDRPp5E9KPVtOh+EooSIhIF19kgk0eCs4fInxQJBAOSKC1iqF65wgAMj6abfXycLQOQ8ihjc+VNZ7k39AlEy1M2TQ14XCIcLUQ9si9f9NJlg/1IbxDvVizsbIOrX12sCQQDFNE6DbBSY0V5AygtKWWyLIR+SMpAEaD1B1y6I09WR2g1LC+P1ZKCTYlqTuuZC4eiwY1M4pdqalMssAG3AXJCTAkEAib11hzPE4Brn3HyplyyrgbGzo5ulM8UC9CyQhyqFWgED5v7prGy/c/zrFxu50SzHpeWjHI6ln9ZdevsnxMLgDwJABpoTrs6leeA4eY7KBfksaxP2zJwouh0LP/MGOcptse5M16BUR1jRD14RjjSJlN+fPJh2psTWpqooixaQlgoDRQJBAJnO+gfeO6weR8CMT6G+Y73PiMtvEyeA0Ew9xRkEkI1ADwglKEarmKgzczxdpjkBFOEOUGbcaLE+1rW9jSwSam8\=
    accessToken: JxZh5nY8Rlaoh3HeK9n8JRPX7qOZw66t
    requestToken: L7QNwPz81Bei4yzY5WRBqiywogcT62qP
    secret: ldCzv9
  url:
    home: "https://auditingapp.atlassian.net"
    accessTokenUrl: ${jira.url.home}/plugins/servlet/oauth/access-token
    requestTokenUrl: ${jira.url.home}/plugins/servlet/oauth/request-token
    authorizationUrl: ${jira.url.home}/plugins/servlet/oauth/authorize
    createMeta: ${jira.url.home}/rest/api/2/issue/createmeta
    createIssue: ${jira.url.home}/rest/api/2/issue
    getIssue: ${jira.url.home}/rest/api/latest/issue/
    getVersions: ${jira.url.home}/rest/api/2/project/${jira.project.id}}/versions
  project:
    id: "AUD"